resources:
  - name: nginx_docker_repo
    type: git
    source:
      uri: git@github.com:marcelocorreia/docker-nginx.git
      branch: master
      paths: nginx_docker_repo
      private_key: {{github_secret_key}}
      username: marcelocorreia

  - name: nginx_dockerfile
    type: git
    source:
      uri: git@github.com:marcelocorreia/docker-nginx.git
      branch: master
      paths: [Dockerfile]
      private_key: {{github_secret_key}}
      username: marcelocorreia


  - name: nginx_image
    type: docker-image
    source:
      repository: marcelocorreia/docker-nginx
      email: {{docker_mail}}
      username: {{docker_user}}
      password: {{docker_password}}

  - name: resource_version
    type: semver
    source:
      driver: git
      uri: git@github.com:marcelocorreia/docker-nginx.git
      branch: version
      file: version
      private_key: {{github_secret_key}}
      username: marcelocorreia


jobs:
  - name: build
    serial: true
    plan:
      - get: nginx_dockerfile
        trigger: true
      - put: resource_version
        params: {pre: rc}
      - put: nginx_image
        params: {build: nginx_dockerfile}
      - put: resource_version
        params: {file: version/version}
