resources:
  - name: nginx_dockerfile
    type: git
    source:
      uri: git@github.com:marcelocorreia/docker-nginx.git
      branch: master
      paths: [Dockerfile]
      private_key: {{github_secret_key}}
      username: marcelocorreia

  - name: nginx_docker_repo
    type: git
    source:
      uri: git@github.com:marcelocorreia/docker-nginx.git
      branch: master
      private_key: {{github_secret_key}}
      username: marcelocorreia

  - name: nginx_image
    type: docker-image
    source:
      repository: marcelocorreia/docker-nginx
      email: {{docker_mail}}
      username: {{docker_user}}
      password: {{docker_password}}

  - name: resource_version
    type: semver
    source:
      driver: git
      initial_version: 0.0.1
      uri: git@github.com:marcelocorreia/docker-nginx.git
      branch: version
      file: version
      private_key: {{github_secret_key}}
      username: marcelocorreia

  - name: gh-release
    type: github-release
    source:
      user: {{github_user}}
      repository: docker-nginx
      access_token: {{github_token}}

jobs:
  - name: build
    serial: true
    plan:
      - get: nginx_dockerfile
        trigger: true
      - get: nginx_docker_repo
        trigger: true
      - put: resource_version
        params: {bump: minor}
      - put: nginx_image
        params: {build: nginx_dockerfile}
      - put: nginx_image
        params: {build: nginx_dockerfile, tag: resource_version/version }
      - put: resource_version
        params: {file: resource_version/version}
      - put: gh-release
        params:
          name: resource_version/version
          tag: resource_version/version