resources:
  - name: nginx_dockerfile
    type: git
    source:
      uri: https://github.com/marcelocorreia/docker-nginx.git
      branch: master
      paths: [Dockerfile]

  - name: nginx_image
    type: docker-image
    source:
     repository: marcelocorreia/docker-nginx
     username: {{ docker_user}}
     password: {{ docker_password }}


jobs:
  - name: build
    plan:
      - get: nginx_dockerfile
        trigger: true
      - put: nginx_image
        params: {build: nginx_dockerfile}

