resources:
  - name: nginx_dockerfile
    type: git
    source:
      uri: https://github.com/marcelocorreia/go-glide-builder.git
      branch: master
      paths: [Dockerfile]

  - name: nginx_image
    type: docker-image
    source:
     repository: marcelocorreia/nginx

jobs:
  - name: build
    plan:
      - get: nginx_dockerfile
        trigger: true
      - put: nginx_image
        params: {build: nginx_dockerfile}
